driver: thermal: thermal: fix build issue caused by merging upstream
When build bcm-2xxx-rpi4 BSP, there is below building error:
error: 't' undeclared (first use in this function); did you mean 'tm'?
This issue is caused by commit c4e1280abead("thermal/drivers/
bcm2711: Don't clamp temperature at zero "). So, remove some
unnecessary code to fix this building error.

Signed-off-by: Meng Li <Meng.Li@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>